modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="homestead" #mandatory
version="${file.jarVersion}" #mandatory
displayName="TFC Homestead Frontiers" #mandatory
logoFile="homestead.png" #optional
credits="Lumintorious, alekiponi" #optional
authors="Love, Cheese and small house plants" #optional
description='''
TFC Homestead Frontiers is a 1.20+ continuation of TFC Homestead.
'''
[[dependencies.homestead]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.homestead]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
